_BASE_: "Base-FCOS.yaml"

MODEL:
  WEIGHTS: "output/fcos/expiry_dates_R_50_1x/model_final.pth"  #detectron2://ImageNetPretrained/MSRA/R-50.pkl
  RESNETS:
    DEPTH: 50
  FCOS:
    NUM_CLASSES: 4  # due, production, code, date

DATASETS:
  TRAIN: ("expiry_dates_train",)
  TEST: ("expiry_dates_val",)

SOLVER:
  IMS_PER_BATCH: 3   # Batch size: 8 images
  BASE_LR: 0.0001   # Learning rate: 0.001 * 8/3 (escalado proporcionalmente)
  STEPS: (18333, 24750)  # 2/3 and 9/10 of 27500
  MAX_ITER: 27500   # 27,500 iterations
  WARMUP_ITERS: 1000
  WARMUP_FACTOR: 0.001
  MOMENTUM: 0.9     # Momentum: 0.9
  WEIGHT_DECAY: 0.0001  # Weight decay: 10^-4

INPUT:
  MIN_SIZE_TRAIN: (800,)  # Short side resized to 800
  MAX_SIZE_TRAIN: 1333    # Long side 1333 or less
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333

OUTPUT_DIR: "output/fcos/expiry_dates_R_50_1x_continue"

# Configuración específica para detección de fechas
TEST:
  EVAL_PERIOD: 5000  # Evaluar cada 5000 iteraciones para monitoreo 